#!/usr/bin/env node
const path = require('node:path');
const crypto = require('node:crypto');
const { JsonStore } = require('./json-store');
const { SqliteStore } = require('./sqlite-store');
const { GitRepositoryService } = require('./git-repository-service');
const { ProjectService } = require('./project-service');
const { MirrorScheduler } = require('./mirror-scheduler');
const { createApp } = require('./app');
const { WorkItemService } = require('./work-item-service');
const { GitHttpBackend } = require('./git-http-backend');
const { ProviderImportService } = require('./provider-import-service');
const { SecretVault } = require('./secret-vault');
const { AuthService } = require('./auth-service');
const { LfsService } = require('./lfs-service');
const { ContentService } = require('./content-service');
const { WebhookService } = require('./webhook-service');
const { GroupService } = require('./group-service');
const { SshKeyService } = require('./ssh-key-service');
const { GitSshServer } = require('./ssh-server');
const { PackageService } = require('./package-service');
const { BoardService } = require('./board-service');
const { NotificationService } = require('./notification-service');
const { SearchService } = require('./search-service');
const { ContainerRegistryService } = require('./container-registry-service');
const { StorageQuotaService } = require('./storage-quota-service');
const { IdentityService } = require('./identity-service');
const { PolicyService } = require('./policy-service');
const { ExternalAuthService } = require('./external-auth-service');
const { UniversalMirrorService } = require('./universal-mirror-service');
const { ReviewService } = require('./review-service');
const { MergeQueueService } = require('./merge-queue-service');
const { DraftService } = require('./draft-service');
const { QualityGateService } = require('./quality-gate-service');
const { PreviewService } = require('./preview-service');
const { AiService } = require('./ai-service');
const { CollaborationRefService } = require('./collaboration-ref-service');
const { ForgeMeshService } = require('./forge-mesh-service');
const { ChangeIntelligenceService } = require('./change-intelligence-service');
const { PolicyEvidenceService } = require('./policy-evidence-service');
const { AttentionService } = require('./attention-service');
const { ChangeBundleService } = require('./change-bundle-service');

function configuration(environment = process.env) {
  const dataPath = path.resolve(environment.KITSUNE_DATA_PATH || path.join(process.cwd(), '.kitsune-web'));
  const host = environment.KITSUNE_HOST || '127.0.0.1';
  const port = Number(environment.KITSUNE_PORT || 4780);
  if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('KITSUNE_PORT is invalid');
  const sshHost = environment.KITSUNE_SSH_HOST || host;
  const sshPort = Number(environment.KITSUNE_SSH_PORT || 0);
  if (!Number.isInteger(sshPort) || sshPort < 0 || sshPort > 65535) throw new Error('KITSUNE_SSH_PORT is invalid');
  const metadataBackend = String(environment.KITSUNE_METADATA_BACKEND || 'json').toLowerCase();
  if (!['json', 'sqlite'].includes(metadataBackend)) throw new Error('KITSUNE_METADATA_BACKEND must be json or sqlite');
  const adminToken = environment.KITSUNE_ADMIN_TOKEN || (host === '127.0.0.1' || host === 'localhost' ? crypto.randomBytes(32).toString('hex') : '');
  const generatedAdminToken = !environment.KITSUNE_ADMIN_TOKEN;
  if (adminToken.length < 24) throw new Error('Set KITSUNE_ADMIN_TOKEN (at least 24 characters) before listening outside localhost');
  const secretKey = environment.KITSUNE_SECRET_KEY || null;
  const lfsMaxObjectBytes = Number(environment.KITSUNE_LFS_MAX_OBJECT_BYTES || 10 * 1024 * 1024 * 1024);
  if (!Number.isSafeInteger(lfsMaxObjectBytes) || lfsMaxObjectBytes < 1024 * 1024) throw new Error('KITSUNE_LFS_MAX_OBJECT_BYTES is invalid');
  const defaultStorageLimitBytes = Number(environment.KITSUNE_PROJECT_STORAGE_LIMIT_BYTES || 0);
  if (!Number.isSafeInteger(defaultStorageLimitBytes) || defaultStorageLimitBytes < 0) throw new Error('KITSUNE_PROJECT_STORAGE_LIMIT_BYTES is invalid');
  if (secretKey && !/^[a-f0-9]{64}$/i.test(secretKey)) throw new Error('KITSUNE_SECRET_KEY must be a 32-byte hexadecimal key');
  const publicUrl = environment.KITSUNE_PUBLIC_URL || '';
  const identityOrigin = environment.KITSUNE_WEBAUTHN_ORIGIN || publicUrl || `http://${host === '0.0.0.0' ? 'localhost' : host}:${port}`;
  let identityUrl; try { identityUrl = new URL(identityOrigin); } catch { throw new Error('KITSUNE_WEBAUTHN_ORIGIN is invalid'); }
  if (!['http:', 'https:'].includes(identityUrl.protocol) || identityUrl.pathname !== '/' || identityUrl.search || identityUrl.hash) throw new Error('KITSUNE_WEBAUTHN_ORIGIN must be a clean HTTP(S) origin');
  const rpId = environment.KITSUNE_WEBAUTHN_RP_ID || identityUrl.hostname;
  if (!/^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)*[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(rpId)) throw new Error('KITSUNE_WEBAUTHN_RP_ID is invalid');
  const oidc = environment.KITSUNE_OIDC_ISSUER ? { issuer: environment.KITSUNE_OIDC_ISSUER, clientId: environment.KITSUNE_OIDC_CLIENT_ID || '', clientSecret: environment.KITSUNE_OIDC_CLIENT_SECRET || '', redirectUri: `${identityUrl.origin}/api/v1/auth/oidc/callback`, scope: environment.KITSUNE_OIDC_SCOPE || 'openid email profile', allowedDomains: String(environment.KITSUNE_OIDC_ALLOWED_DOMAINS || '').split(',').map(value => value.trim().toLowerCase()).filter(Boolean) } : null;
  if (oidc && !oidc.clientId) throw new Error('KITSUNE_OIDC_CLIENT_ID is required with OIDC');
  const ldap = environment.KITSUNE_LDAP_URL ? { url: environment.KITSUNE_LDAP_URL, baseDN: environment.KITSUNE_LDAP_BASE_DN || '', bindDN: environment.KITSUNE_LDAP_BIND_DN || '', bindPassword: environment.KITSUNE_LDAP_BIND_PASSWORD || '', userFilter: environment.KITSUNE_LDAP_USER_FILTER || '(uid={{username}})', usernameAttribute: environment.KITSUNE_LDAP_USERNAME_ATTRIBUTE || 'uid', emailAttribute: environment.KITSUNE_LDAP_EMAIL_ATTRIBUTE || 'mail', nameAttribute: environment.KITSUNE_LDAP_NAME_ATTRIBUTE || 'displayName', rejectUnauthorized: environment.KITSUNE_LDAP_TLS_REJECT_UNAUTHORIZED !== 'false' } : null;
  if (ldap && !ldap.baseDN) throw new Error('KITSUNE_LDAP_BASE_DN is required with LDAP');
  const previewProvisionerUrl = environment.KITSUNE_PREVIEW_PROVISIONER_URL || '';
  const previewSecret = environment.KITSUNE_PREVIEW_SECRET || '';
  if (Boolean(previewProvisionerUrl) !== Boolean(previewSecret)) throw new Error('KITSUNE_PREVIEW_PROVISIONER_URL and KITSUNE_PREVIEW_SECRET must be configured together');
  const aiProvider = environment.KITSUNE_AI_PROVIDER ? { type: environment.KITSUNE_AI_PROVIDER, baseUrl: environment.KITSUNE_AI_BASE_URL || '', model: environment.KITSUNE_AI_MODEL || '', apiKey: environment.KITSUNE_AI_API_KEY || '' } : null;
  if (aiProvider && (!aiProvider.baseUrl || !aiProvider.model)) throw new Error('KITSUNE_AI_BASE_URL and KITSUNE_AI_MODEL are required with KITSUNE_AI_PROVIDER');
  let aiProviders = null; if (environment.KITSUNE_AI_PROVIDERS_JSON) { try { aiProviders = JSON.parse(environment.KITSUNE_AI_PROVIDERS_JSON); } catch { throw new Error('KITSUNE_AI_PROVIDERS_JSON must contain valid JSON'); } if (!Array.isArray(aiProviders) || aiProviders.length > 20) throw new Error('KITSUNE_AI_PROVIDERS_JSON must be an array with at most 20 providers'); }
  return { dataPath, host, port, sshHost, sshPort, metadataBackend, adminToken, generatedAdminToken, secretKey, lfsMaxObjectBytes, defaultStorageLimitBytes, publicUrl, identityOrigin: identityUrl.origin, rpId, oidc, ldap, previewProvisionerUrl, previewSecret, aiProvider, aiProviders, gitExecutable: environment.KITSUNE_GIT_EXECUTABLE || 'git' };
}

function start(environment = process.env) {
  const config = configuration(environment);
  const store = config.metadataBackend === 'sqlite' ? new SqliteStore(path.join(config.dataPath, 'database.sqlite')) : new JsonStore(path.join(config.dataPath, 'database.json'));
  const repositories = new GitRepositoryService({ repositoriesPath: path.join(config.dataPath, 'repositories'), gitExecutable: config.gitExecutable });
  const secretVault = config.secretKey ? new SecretVault(config.secretKey) : null;
  const providerImports = new ProviderImportService();
  const projects = new ProjectService({ store, repositories, providerImports, secretVault, defaultStorageLimitBytes: config.defaultStorageLimitBytes });
  for (const project of projects.list()) repositories.installHooks(project);
  const auth = new AuthService({ store, adminToken: config.adminToken });
  const policy = new PolicyService({ store, projects, auth });
  const collaborationRefs = new CollaborationRefService({ store, projects, dataPath: config.dataPath });
  const qualityGates = new QualityGateService({ store, projects, secretVault, publicUrl: config.publicUrl || config.identityOrigin });
  const previews = new PreviewService({ store, projects, provisionerUrl: config.previewProvisionerUrl, provisionerSecret: config.previewSecret });
  const workItems = new WorkItemService({ store, projects, policy, qualityGates });
  const reviews = new ReviewService({ projects, store, policy });
  const ai = new AiService({ store, projects, reviews, provider: config.aiProvider, providers: config.aiProviders });
  const forgeMesh = new ForgeMeshService({ store, projects, providerImports, secretVault });
  const changeIntelligence = new ChangeIntelligenceService({ store, projects, reviews, policy });
  const mergeQueue = new MergeQueueService({ store, workItems, policy });
  const drafts = new DraftService({ store, auth, workItems });
  const policyEvidence = new PolicyEvidenceService({ store, projects, policy, workItems, qualityGates, collaborationRefs });
  const changeBundles = new ChangeBundleService({ store, projects, policyEvidence, collaborationRefs, dataPath: config.dataPath });
  const attention = new AttentionService({ store, projects, auth, policy });
  const identity = new IdentityService({ store, auth, secretVault, rpId: config.rpId, origin: config.identityOrigin });
  const externalAuth = new ExternalAuthService({ store, identity, oidc: config.oidc, ldap: config.ldap });
  const mirrors = new UniversalMirrorService({ store, projects, providerImports });
  const groups = new GroupService({ store });
  const sshKeys = new SshKeyService({ store });
  const quota = new StorageQuotaService({ dataPath: config.dataPath, projects, defaultLimitBytes: config.defaultStorageLimitBytes });
  const packages = new PackageService({ dataPath: config.dataPath, store, projects, quota });
  const registry = new ContainerRegistryService({ dataPath: config.dataPath, store, projects, auth, quota });
  const boards = new BoardService({ store, projects });
  const notifications = new NotificationService({ store });
  const search = new SearchService({ store, projects, auth });
  const lfs = new LfsService({ dataPath: config.dataPath, projects, auth, quota, publicUrl: config.publicUrl, maxObjectBytes: config.lfsMaxObjectBytes });
  const content = new ContentService({ store, projects });
  const webhooks = new WebhookService({ store, projects, secretVault: projects.secretVault });
  const gitBackend = new GitHttpBackend({ repositoriesPath: repositories.repositoriesPath, databasePath: store.filePath, adminToken: config.adminToken, auth, gitExecutable: config.gitExecutable, projects });
  const scheduler = new MirrorScheduler({ projects, mirrors, store });
  const server = createApp({ projects, groups, workItems, policy, mirrors, forgeMesh, collaborationRefs, changeIntelligence, policyEvidence, changeBundles, attention, reviews, mergeQueue, drafts, qualityGates, previews, ai, content, webhooks, gitBackend, lfs, sshKeys, packages, registry, quota, boards, notifications, search, identity, externalAuth, auth, store, adminToken: config.adminToken });
  const sshServer = config.sshPort ? new GitSshServer({ dataPath: config.dataPath, projects, repositories, auth, keys: sshKeys, gitExecutable: config.gitExecutable }) : null;
  server.listen(config.port, config.host, () => {
    console.log(`KitsuneGIT Web: http://${config.host}:${config.port}`);
    console.log(config.generatedAdminToken ? `Temporary local admin token: ${config.adminToken}` : 'Administrator token loaded from the environment');
    if (sshServer) sshServer.listen(config.sshPort, config.sshHost, () => console.log(`KitsuneGIT SSH: ssh://git@${config.sshHost}:${config.sshPort}`));
    scheduler.start();
  });
  const previewTimer = previews.enabled() ? setInterval(() => { void previews.cleanup(); }, 15 * 60_000) : null;
  previewTimer?.unref();
  const close = () => { scheduler.stop(); if (previewTimer) clearInterval(previewTimer); sshServer?.close(); server.close(() => { store.close?.(); process.exit(0); }); };
  process.once('SIGINT', close);
  process.once('SIGTERM', close);
  return { server, sshServer, scheduler, projects, workItems, config };
}

if (require.main === module) start();

module.exports = { configuration, start };
