const crypto = require('node:crypto');
const { promisify } = require('node:util');
const { generateRegistrationOptions, verifyRegistrationResponse, generateAuthenticationOptions, verifyAuthenticationResponse } = require('@simplewebauthn/server');
const { slug, text } = require('./validation');
const { tokenHash } = require('./auth-service');

const scrypt = promisify(crypto.scrypt);
const SESSION_HOURS = 12;
const CHALLENGE_MINUTES = 5;

function email(value) { const normalized = String(value || '').trim().toLowerCase(); if (normalized.length > 320 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized)) throw new Error('Email address is invalid'); return normalized; }
function passwordValue(value) { const normalized = String(value || ''); if (Buffer.byteLength(normalized) < 12 || Buffer.byteLength(normalized) > 1024 || normalized.includes('\0')) throw new Error('Password must contain 12–1024 bytes'); return normalized; }
function randomToken(prefix) { return `${prefix}_${crypto.randomBytes(32).toString('base64url')}`; }
function safeEqual(left, right) { const a = Buffer.from(String(left || '')); const b = Buffer.from(String(right || '')); return a.length === b.length && crypto.timingSafeEqual(a, b); }

async function hashPassword(password) {
  const salt = crypto.randomBytes(16); const derived = await scrypt(passwordValue(password), salt, 64, { N: 2 ** 17, r: 8, p: 1, maxmem: 192 * 1024 * 1024 });
  return `scrypt$131072$8$1$${salt.toString('base64url')}$${derived.toString('base64url')}`;
}
async function verifyPassword(password, encoded) {
  const parts = String(encoded || '').split('$'); if (parts.length !== 6 || parts[0] !== 'scrypt') return false;
  const [, n, r, p, saltValue, hashValue] = parts; const expected = Buffer.from(hashValue, 'base64url');
  const actual = await scrypt(String(password || ''), Buffer.from(saltValue, 'base64url'), expected.length, { N: Number(n), r: Number(r), p: Number(p), maxmem: 192 * 1024 * 1024 });
  return actual.length === expected.length && crypto.timingSafeEqual(actual, expected);
}

const BASE32 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
function base32(buffer) { let bits = ''; for (const byte of buffer) bits += byte.toString(2).padStart(8, '0'); let result = ''; for (let index = 0; index < bits.length; index += 5) result += BASE32[Number.parseInt(bits.slice(index, index + 5).padEnd(5, '0'), 2)]; return result; }
function fromBase32(value) { let bits = ''; for (const character of String(value).replace(/=+$/g, '').toUpperCase()) { const index = BASE32.indexOf(character); if (index < 0) throw new Error('TOTP secret is invalid'); bits += index.toString(2).padStart(5, '0'); } const bytes = []; for (let index = 0; index + 8 <= bits.length; index += 8) bytes.push(Number.parseInt(bits.slice(index, index + 8), 2)); return Buffer.from(bytes); }
function totp(secret, time = Date.now()) { const counter = Math.floor(time / 30_000); const value = Buffer.alloc(8); value.writeBigUInt64BE(BigInt(counter)); const hash = crypto.createHmac('sha1', fromBase32(secret)).update(value).digest(); const offset = hash[19] & 15; return String((hash.readUInt32BE(offset) & 0x7fffffff) % 1_000_000).padStart(6, '0'); }
function verifyTotp(secret, code, time = Date.now()) { return [-1, 0, 1].some(offset => safeEqual(totp(secret, time + offset * 30_000), String(code || '').replace(/\s/g, ''))); }

class IdentityService {
  constructor({ store, auth, secretVault = null, rpName = 'KitsuneGIT', rpId = 'localhost', origin = 'http://localhost:4780' }) { this.store = store; this.auth = auth; this.secretVault = secretVault; this.rpName = rpName; this.rpId = rpId; this.origin = origin.replace(/\/$/, ''); this.attempts = new Map(); }
  _user(identifier) { const normalized = String(identifier || '').trim().toLowerCase(); return this.store.snapshot().users.find(item => !item.blocked && (item.username === normalized || item.email === normalized)); }
  _publicUser(user) { const { tokenHashes, passwordHash, totpSecret, ...safe } = user; return { ...safe, tokenCount: tokenHashes?.length || 0, passwordEnabled: Boolean(passwordHash), totpEnabled: Boolean(totpSecret), passkeyCount: this.store.snapshot().passkeys.filter(item => item.userId === user.id).length }; }
  _rateLimit(key) { const now = Date.now(); const current = this.attempts.get(key) || []; const recent = current.filter(value => now - value < 15 * 60_000); if (recent.length >= 10) throw Object.assign(new Error('Too many authentication attempts'), { statusCode: 429 }); recent.push(now); this.attempts.set(key, recent); }
  _clearRateLimit(key) { this.attempts.delete(key); }
  bootstrapAvailable() { return !this.store.snapshot().users.some(user => user.admin); }
  async bootstrapAdmin(input, context = {}) {
    if (!this.bootstrapAvailable()) throw Object.assign(new Error('Administrator account is already registered'), { statusCode: 409 });
    const username = slug(input.username, 'Username');
    const targetEmail = email(input.email);
    const name = text(input.name, 'Name', { max: 256, required: true });
    const passwordHash = await hashPassword(input.password);
    const now = new Date().toISOString();
    const user = { id: crypto.randomUUID(), username, email: targetEmail, emailVerifiedAt: now, name, admin: true, blocked: false, passwordHash, passwordChangedAt: now, tokenHashes: [], createdAt: now };
    const saved = this.store.update(state => {
      if (state.users.some(item => item.admin)) throw Object.assign(new Error('Administrator account is already registered'), { statusCode: 409 });
      if (state.users.some(item => item.username === username || item.email === targetEmail)) throw Object.assign(new Error('Username or email address is already registered'), { statusCode: 409 });
      state.users.push(user);
      return user;
    }, { actor: 'bootstrap', action: 'identity.bootstrap-admin', target: user.id });
    return this._session(saved, context, 'bootstrap');
  }
  async setPassword(userId, password, actor) { if (!actor?.admin && actor?.id !== userId) throw Object.assign(new Error('Forbidden'), { statusCode: 403 }); const encoded = await hashPassword(password); return this.store.update(state => { const user = state.users.find(item => item.id === userId); if (!user) throw Object.assign(new Error('User not found'), { statusCode: 404 }); user.passwordHash = encoded; user.passwordChangedAt = new Date().toISOString(); state.sessions = state.sessions.filter(item => item.userId !== userId || item.id === actor.sessionId); return this._publicUser(user); }, { actor: actor.username, action: 'identity.password-set', target: userId }); }
  async login(input, context = {}) { const key = `${context.ip || ''}:${String(input.identifier || '').toLowerCase()}`; this._rateLimit(key); const user = this._user(input.identifier); const valid = user ? await verifyPassword(input.password, user.passwordHash) : await hashPassword('invalid-password-value').then(() => false); if (!valid) throw Object.assign(new Error('Invalid credentials'), { statusCode: 401 }); if (user.totpSecret) { const ticket = this._challenge('totp-login', user.id); return { mfaRequired: true, ticket: ticket.token }; } this._clearRateLimit(key); return this._session(user, context, 'password'); }
  _session(user, context, method) { const token = randomToken('kgs'); const csrfToken = randomToken('csrf'); const now = Date.now(); const session = { id: crypto.randomUUID(), userId: user.id, tokenHash: tokenHash(token), csrfToken, method, userAgent: String(context.userAgent || '').slice(0, 512), ip: String(context.ip || '').slice(0, 128), createdAt: new Date(now).toISOString(), lastSeenAt: new Date(now).toISOString(), expiresAt: new Date(now + SESSION_HOURS * 3600_000).toISOString() }; this.store.update(state => { state.sessions.push(session); state.sessions = state.sessions.filter(item => Date.parse(item.expiresAt) > now).slice(-20_000); return null; }, { actor: user.username, action: 'session.create', target: session.id }); return { user: this._publicUser(user), session: { token, csrfToken, expiresAt: session.expiresAt } }; }
  establishExternal(provider, subject, profile, context = {}) {
    const providerName = text(provider, 'Identity provider', { max: 64, required: true }); const externalSubject = text(subject, 'External subject', { max: 512, required: true }); const targetEmail = email(profile.email); const state = this.store.snapshot();
    let user = state.users.find(item => (item.externalIdentities || []).some(identity => identity.provider === providerName && identity.subject === externalSubject));
    if (!user) user = state.users.find(item => item.email === targetEmail);
    if (!user) {
      const base = String(profile.username || targetEmail.split('@')[0]).toLowerCase().replace(/[^a-z0-9._-]/g, '-').replace(/^-+|-+$/g, '').slice(0, 56) || 'user'; let username = base; let suffix = 1; while (state.users.some(item => item.username === username)) username = `${base}-${suffix++}`;
      user = { id: crypto.randomUUID(), username, email: targetEmail, emailVerifiedAt: new Date().toISOString(), name: text(profile.name || username, 'Name', { max: 256, required: true }), admin: false, blocked: false, tokenHashes: [], externalIdentities: [], createdAt: new Date().toISOString() };
    }
    const saved = this.store.update(draft => { let current = draft.users.find(item => item.id === user.id); if (!current) { draft.users.push(user); current = user; } current.externalIdentities ||= []; if (!current.externalIdentities.some(item => item.provider === providerName && item.subject === externalSubject)) current.externalIdentities.push({ provider: providerName, subject: externalSubject, linkedAt: new Date().toISOString() }); if (!current.emailVerifiedAt) current.emailVerifiedAt = new Date().toISOString(); return current; }, { actor: `${providerName}:${externalSubject}`, action: 'identity.external-login', target: user.id });
    return this._session(saved, context, providerName);
  }
  sessionCookie(token, secure = true) { return `kitsune_session=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${SESSION_HOURS * 3600}${secure ? '; Secure' : ''}`; }
  clearCookie(secure = true) { return `kitsune_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${secure ? '; Secure' : ''}`; }
  logout(actor) { if (!actor?.sessionId) return; this.store.update(state => { state.sessions = state.sessions.filter(item => item.id !== actor.sessionId); return null; }, { actor: actor.username, action: 'session.revoke', target: actor.sessionId }); }
  sessions(actor) { return this.store.snapshot().sessions.filter(item => actor.admin || item.userId === actor.id).map(({ tokenHash: ignored, csrfToken: hidden, ...item }) => item); }
  revokeSession(id, actor) { return this.store.update(state => { const session = state.sessions.find(item => item.id === id); if (!session || (!actor.admin && session.userId !== actor.id)) throw Object.assign(new Error('Session not found'), { statusCode: 404 }); state.sessions = state.sessions.filter(item => item.id !== id); return { id }; }, { actor: actor.username, action: 'session.revoke', target: id }); }
  createInvitation(input, actor) { this.auth.requireAdmin(actor); const targetEmail = email(input.email); const username = slug(input.username || targetEmail.split('@')[0], 'Username'); if (this.store.snapshot().users.some(item => item.username === username || item.email === targetEmail)) throw Object.assign(new Error('User already exists'), { statusCode: 409 }); const token = randomToken('invite'); const invitation = { id: crypto.randomUUID(), email: targetEmail, username, name: text(input.name || username, 'Name', { max: 256, required: true }), tokenHash: tokenHash(token), expiresAt: new Date(Date.now() + 7 * 86400_000).toISOString(), createdAt: new Date().toISOString(), acceptedAt: null }; this.store.update(state => { state.invitations.push(invitation); return null; }, { actor: actor.username, action: 'invitation.create', target: invitation.id }); return { invitation: { ...invitation, tokenHash: undefined }, token }; }
  async acceptInvitation(input, context = {}) { const hash = tokenHash(input.token); const invitation = this.store.snapshot().invitations.find(item => item.tokenHash === hash && !item.acceptedAt && Date.parse(item.expiresAt) > Date.now()); if (!invitation) throw Object.assign(new Error('Invitation is invalid or expired'), { statusCode: 400 }); const encoded = await hashPassword(input.password); const user = { id: crypto.randomUUID(), username: invitation.username, email: invitation.email, emailVerifiedAt: new Date().toISOString(), name: invitation.name, admin: false, blocked: false, passwordHash: encoded, tokenHashes: [], createdAt: new Date().toISOString() }; this.store.update(state => { const current = state.invitations.find(item => item.id === invitation.id); if (!current || current.acceptedAt) throw Object.assign(new Error('Invitation was already accepted'), { statusCode: 409 }); current.acceptedAt = new Date().toISOString(); state.users.push(user); return null; }, { actor: user.username, action: 'invitation.accept', target: invitation.id }); return this._session(user, context, 'password'); }
  createPasswordReset(userId, actor) { this.auth.requireAdmin(actor); const user = this.store.snapshot().users.find(item => item.id === userId); if (!user) throw Object.assign(new Error('User not found'), { statusCode: 404 }); const token = randomToken('reset'); const item = { id: crypto.randomUUID(), userId, tokenHash: tokenHash(token), expiresAt: new Date(Date.now() + 3600_000).toISOString(), usedAt: null, createdAt: new Date().toISOString() }; this.store.update(state => { state.passwordResets.push(item); return null; }, { actor: actor.username, action: 'password-reset.create', target: userId }); return { token, expiresAt: item.expiresAt }; }
  async completePasswordReset(input) { const hash = tokenHash(input.token); const item = this.store.snapshot().passwordResets.find(value => value.tokenHash === hash && !value.usedAt && Date.parse(value.expiresAt) > Date.now()); if (!item) throw Object.assign(new Error('Password reset is invalid or expired'), { statusCode: 400 }); const encoded = await hashPassword(input.password); this.store.update(state => { const reset = state.passwordResets.find(value => value.id === item.id); reset.usedAt = new Date().toISOString(); const user = state.users.find(value => value.id === item.userId); user.passwordHash = encoded; user.passwordChangedAt = reset.usedAt; state.sessions = state.sessions.filter(value => value.userId !== user.id); return null; }, { actor: 'password-reset', action: 'password-reset.complete', target: item.userId }); return { reset: true }; }
  beginTotp(actor) { if (!this.secretVault) throw new Error('KITSUNE_SECRET_KEY is required for TOTP'); const secret = base32(crypto.randomBytes(20)); const challenge = this._challenge('totp-enroll', actor.id, { encryptedSecret: this.secretVault.encrypt(secret) }); return { ticket: challenge.token, secret, uri: `otpauth://totp/${encodeURIComponent(this.rpName)}:${encodeURIComponent(actor.username)}?secret=${secret}&issuer=${encodeURIComponent(this.rpName)}&algorithm=SHA1&digits=6&period=30` }; }
  confirmTotp(input, actor) { const challenge = this._consumeChallenge(input.ticket, 'totp-enroll', actor.id); const secret = this.secretVault.decrypt(challenge.encryptedSecret); if (!verifyTotp(secret, input.code)) throw Object.assign(new Error('TOTP code is invalid'), { statusCode: 400 }); this.store.update(state => { const user = state.users.find(item => item.id === actor.id); user.totpSecret = this.secretVault.encrypt(secret); return null; }, { actor: actor.username, action: 'totp.enable', target: actor.id }); return { enabled: true }; }
  completeTotpLogin(input, context = {}) { const challenge = this._consumeChallenge(input.ticket, 'totp-login'); const user = this.store.snapshot().users.find(item => item.id === challenge.userId && !item.blocked); if (!user?.totpSecret || !verifyTotp(this.secretVault.decrypt(user.totpSecret), input.code)) throw Object.assign(new Error('TOTP code is invalid'), { statusCode: 401 }); return this._session(user, context, 'password+totp'); }
  _challenge(purpose, userId, data = {}) { const token = randomToken('challenge'); const item = { id: crypto.randomUUID(), purpose, userId, tokenHash: tokenHash(token), ...data, expiresAt: new Date(Date.now() + CHALLENGE_MINUTES * 60_000).toISOString(), createdAt: new Date().toISOString() }; this.store.update(state => { state.authChallenges.push(item); state.authChallenges = state.authChallenges.filter(value => Date.parse(value.expiresAt) > Date.now()).slice(-10_000); return null; }); return { ...item, token }; }
  _consumeChallenge(token, purpose, userId = null) { const hash = tokenHash(token); return this.store.update(state => { const index = state.authChallenges.findIndex(item => item.tokenHash === hash && item.purpose === purpose && (!userId || item.userId === userId) && Date.parse(item.expiresAt) > Date.now()); if (index < 0) throw Object.assign(new Error('Authentication challenge is invalid or expired'), { statusCode: 400 }); return state.authChallenges.splice(index, 1)[0]; }); }
  async passkeyRegistrationOptions(actor) { const credentials = this.store.snapshot().passkeys.filter(item => item.userId === actor.id); const options = await generateRegistrationOptions({ rpName: this.rpName, rpID: this.rpId, userName: actor.username, userDisplayName: actor.name || actor.username, userID: Buffer.from(actor.id), attestationType: 'none', excludeCredentials: credentials.map(item => ({ id: item.credentialId, transports: item.transports })), authenticatorSelection: { residentKey: 'preferred', userVerification: 'required' } }); const challenge = this._challenge('passkey-register', actor.id, { webauthnChallenge: options.challenge }); return { ticket: challenge.token, options }; }
  async verifyPasskeyRegistration(input, actor) { const challenge = this._consumeChallenge(input.ticket, 'passkey-register', actor.id); const result = await verifyRegistrationResponse({ response: input.response, expectedChallenge: challenge.webauthnChallenge, expectedOrigin: this.origin, expectedRPID: this.rpId, requireUserVerification: true }); if (!result.verified || !result.registrationInfo) throw Object.assign(new Error('Passkey registration failed'), { statusCode: 400 }); const credential = result.registrationInfo.credential; const item = { id: crypto.randomUUID(), userId: actor.id, name: text(input.name || 'Passkey', 'Passkey name', { max: 128, required: true }), credentialId: credential.id, publicKey: Buffer.from(credential.publicKey).toString('base64'), counter: credential.counter, transports: credential.transports || [], deviceType: result.registrationInfo.credentialDeviceType, backedUp: result.registrationInfo.credentialBackedUp, createdAt: new Date().toISOString(), lastUsedAt: null }; this.store.update(state => { if (state.passkeys.some(value => value.credentialId === item.credentialId)) throw Object.assign(new Error('Passkey already exists'), { statusCode: 409 }); state.passkeys.push(item); return null; }, { actor: actor.username, action: 'passkey.create', target: item.id }); return { ...item, publicKey: undefined }; }
  passkeys(actor) { return this.store.snapshot().passkeys.filter(item => item.userId === actor.id).map(({ publicKey, ...item }) => item); }
  removePasskey(id, actor) { return this.store.update(state => { const index = state.passkeys.findIndex(item => item.id === id && (item.userId === actor.id || actor.admin)); if (index < 0) throw Object.assign(new Error('Passkey not found'), { statusCode: 404 }); const item = state.passkeys.splice(index, 1)[0]; return { id: item.id }; }, { actor: actor.username, action: 'passkey.remove', target: id }); }
  async passkeyAuthenticationOptions(identifier) { const user = this._user(identifier); if (!user) throw Object.assign(new Error('Passkey account not found'), { statusCode: 404 }); const credentials = this.store.snapshot().passkeys.filter(item => item.userId === user.id); if (!credentials.length) throw Object.assign(new Error('No passkeys are registered'), { statusCode: 404 }); const options = await generateAuthenticationOptions({ rpID: this.rpId, allowCredentials: credentials.map(item => ({ id: item.credentialId, transports: item.transports })), userVerification: 'required' }); const challenge = this._challenge('passkey-login', user.id, { webauthnChallenge: options.challenge }); return { ticket: challenge.token, options }; }
  async verifyPasskeyAuthentication(input, context = {}) { const challenge = this._consumeChallenge(input.ticket, 'passkey-login'); const passkey = this.store.snapshot().passkeys.find(item => item.userId === challenge.userId && item.credentialId === input.response?.id); if (!passkey) throw Object.assign(new Error('Passkey not found'), { statusCode: 404 }); const result = await verifyAuthenticationResponse({ response: input.response, expectedChallenge: challenge.webauthnChallenge, expectedOrigin: this.origin, expectedRPID: this.rpId, credential: { id: passkey.credentialId, publicKey: Buffer.from(passkey.publicKey, 'base64'), counter: passkey.counter, transports: passkey.transports }, requireUserVerification: true }); if (!result.verified) throw Object.assign(new Error('Passkey authentication failed'), { statusCode: 401 }); const user = this.store.snapshot().users.find(item => item.id === challenge.userId && !item.blocked); this.store.update(state => { const current = state.passkeys.find(item => item.id === passkey.id); current.counter = result.authenticationInfo.newCounter; current.lastUsedAt = new Date().toISOString(); return null; }); return this._session(user, context, 'passkey'); }
}

module.exports = { IdentityService, hashPassword, verifyPassword, totp, verifyTotp, email };
