const crypto = require('node:crypto');
const { text } = require('./validation');
const { ROLE_LEVEL, activeMembership } = require('./auth-service');

function globRegex(pattern) {
  let value = String(pattern || '').trim(); const anchored = value.startsWith('/'); if (anchored) value = value.slice(1); const directory = value.endsWith('/'); if (directory) value = value.slice(0, -1);
  let source = ''; for (let index = 0; index < value.length; index += 1) { const character = value[index]; if (character === '*' && value[index + 1] === '*') { source += '.*'; index += 1; } else if (character === '*') source += '[^/]*'; else if (character === '?') source += '[^/]'; else source += character.replace(/[|\\{}()[\]^$+?.]/g, '\\$&'); }
  if (!anchored && !value.includes('/')) source = `(?:^|.*/)${source}`; else source = `^${source}`; return new RegExp(`${source}${directory ? '(?:/.*)?' : ''}$`);
}
function branchMatches(pattern, branch) { return globRegex(pattern || '*').test(branch); }

class PolicyService {
  constructor({ store, projects, auth }) { this.store = store; this.projects = projects; this.auth = auth; }
  explain(projectId, userId, required = 'guest') {
    const project = this.projects.get(projectId); const state = this.store.snapshot(); const user = state.users.find(item => item.id === userId); if (!user) throw Object.assign(new Error('User not found'), { statusCode: 404 });
    const sources = []; if (user.admin) sources.push({ type: 'administrator', role: 'owner', reason: 'Instance administrator bypass' });
    if (required === 'guest' && project.visibility === 'public') sources.push({ type: 'visibility', role: 'guest', reason: 'Public project' });
    const direct = state.memberships.find(item => item.projectId === projectId && item.userId === userId); if (direct) sources.push({ type: 'project', role: direct.role, active: activeMembership(direct), expiresAt: direct.expiresAt || null, reason: activeMembership(direct) ? 'Direct project membership' : 'Direct membership expired' });
    let group = project.groupId ? state.groups.find(item => item.id === project.groupId) : null; const seen = new Set(); while (group && !seen.has(group.id)) { seen.add(group.id); const membership = state.groupMemberships.find(item => item.groupId === group.id && item.userId === userId); if (membership) sources.push({ type: 'group', groupId: group.id, groupPath: group.fullPath, role: membership.role, active: activeMembership(membership), expiresAt: membership.expiresAt || null, reason: activeMembership(membership) ? `Inherited from ${group.fullPath}` : `Expired membership in ${group.fullPath}` }); group = group.parentId ? state.groups.find(item => item.id === group.parentId) : null; }
    const effective = sources.filter(item => item.active !== false).sort((a, b) => (ROLE_LEVEL[b.role] || 0) - (ROLE_LEVEL[a.role] || 0))[0]?.role || null; const allowed = Boolean(user.admin || (effective && ROLE_LEVEL[effective] >= ROLE_LEVEL[required]));
    return { projectId, user: { id: user.id, username: user.username }, requiredRole: required, effectiveRole: effective, allowed, sources, explanation: allowed ? `${effective || 'administrator'} satisfies ${required}` : `No active role satisfies ${required}` };
  }
  explainAt(projectId, userId, required = 'guest', at = new Date().toISOString()) { const timestamp = Date.parse(at); if (!Number.isFinite(timestamp)) throw new Error('Policy evaluation time is invalid'); const project = this.projects.get(projectId); const state = this.store.snapshot(); const user = state.users.find(item => item.id === userId); if (!user) throw Object.assign(new Error('User not found'), { statusCode: 404 }); const sources = []; if (user.admin) sources.push({ type: 'administrator', role: 'owner', active: true, reason: 'Instance administrator bypass' }); if (required === 'guest' && project.visibility === 'public') sources.push({ type: 'visibility', role: 'guest', active: true, reason: 'Public project' }); const direct = state.memberships.find(item => item.projectId === projectId && item.userId === userId); if (direct) sources.push({ type: 'project', role: direct.role, active: activeMembership(direct, timestamp), expiresAt: direct.expiresAt || null, reason: activeMembership(direct, timestamp) ? 'Direct project membership' : 'Direct membership expired' }); let group = project.groupId ? state.groups.find(item => item.id === project.groupId) : null; const seen = new Set(); while (group && !seen.has(group.id)) { seen.add(group.id); const membership = state.groupMemberships.find(item => item.groupId === group.id && item.userId === userId); if (membership) sources.push({ type: 'group', groupId: group.id, groupPath: group.fullPath, role: membership.role, active: activeMembership(membership, timestamp), expiresAt: membership.expiresAt || null, reason: activeMembership(membership, timestamp) ? `Inherited from ${group.fullPath}` : `Expired membership in ${group.fullPath}` }); group = group.parentId ? state.groups.find(item => item.id === group.parentId) : null; } const effective = sources.filter(item => item.active !== false).sort((a, b) => (ROLE_LEVEL[b.role] || 0) - (ROLE_LEVEL[a.role] || 0))[0]?.role || null; return { projectId, evaluatedAt: new Date(timestamp).toISOString(), user: { id: user.id, username: user.username }, requiredRole: required, effectiveRole: effective, allowed: Boolean(user.admin || (effective && ROLE_LEVEL[effective] >= ROLE_LEVEL[required])), sources }; }
  forecast(projectId, days = 30) { this.projects.get(projectId); const horizon = Date.now() + Math.max(1, Math.min(365, Number(days) || 30)) * 86400_000; const state = this.store.snapshot(); const memberships = [...state.memberships.filter(item => item.projectId === projectId), ...state.groupMemberships.filter(item => { const groups = new Set(); let group = state.projects.find(project => project.id === projectId)?.groupId; while (group) { groups.add(group); group = state.groups.find(item => item.id === group)?.parentId; } return groups.has(item.groupId); })]; return memberships.filter(item => item.expiresAt && Date.parse(item.expiresAt) <= horizon && Date.parse(item.expiresAt) > Date.now()).map(item => { const user = state.users.find(value => value.id === item.userId); const before = this.explainAt(projectId, item.userId, 'guest', new Date(Date.parse(item.expiresAt) - 1).toISOString()); const after = this.explainAt(projectId, item.userId, 'guest', new Date(Date.parse(item.expiresAt) + 1).toISOString()); return { user: { id: user?.id, username: user?.username }, expiresAt: item.expiresAt, role: item.role, source: item.projectId ? 'project' : 'group', effectiveRoleBefore: before.effectiveRole, effectiveRoleAfter: after.effectiveRole, losesAccess: before.allowed && !after.allowed }; }).sort((a, b) => Date.parse(a.expiresAt) - Date.parse(b.expiresAt)); }
  listRulesets(projectId) { this.projects.get(projectId); return this.store.snapshot().projectRulesets.filter(item => item.projectId === projectId); }
  saveRuleset(projectId, input, actor) {
    this.projects.get(projectId); const reviewers = Array.isArray(input.requiredReviewers) ? [...new Set(input.requiredReviewers.slice(0, 50).map(value => text(value, 'Required reviewer', { max: 64, required: true }).replace(/^@/, '')))] : [];
    const item = { id: input.id || crypto.randomUUID(), projectId, name: text(input.name, 'Ruleset name', { max: 128, required: true }), branchPattern: text(input.branchPattern || '*', 'Branch pattern', { max: 256, required: true }), enforcement: input.enforcement === 'evaluate' ? 'evaluate' : 'active', requiredApprovals: Math.max(0, Math.min(20, Number(input.requiredApprovals) || 0)), requiredReviewers: reviewers, requireCodeOwners: Boolean(input.requireCodeOwners), dismissStaleApprovals: input.dismissStaleApprovals !== false, requireMergeQueue: Boolean(input.requireMergeQueue), requiredQualityGates: Array.isArray(input.requiredQualityGates) ? input.requiredQualityGates.slice(0, 20).map(value => text(value, 'Quality gate', { max: 128, required: true })) : [], createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }; branchMatches(item.branchPattern, 'main');
    return this.store.update(state => { const index = state.projectRulesets.findIndex(value => value.id === item.id && value.projectId === projectId); if (index >= 0) { item.createdAt = state.projectRulesets[index].createdAt; state.projectRulesets[index] = item; } else state.projectRulesets.push(item); return item; }, { actor, action: 'ruleset.save', target: item.id });
  }
  matchingRules(projectId, branch) { return this.listRulesets(projectId).filter(item => branchMatches(item.branchPattern, branch)); }
  async codeOwners(project, files) { const locations = ['.github/CODEOWNERS', 'CODEOWNERS', 'docs/CODEOWNERS']; let content = ''; for (const location of locations) { try { content = (await this.projects.repositories.run(['show', `${project.defaultBranch || 'main'}:${location}`], { cwd: this.projects.repositories.pathFor(project) })).stdout; if (content) break; } catch {} } const rules = content.split('\n').map(line => line.replace(/\s+#.*$/, '').trim()).filter(line => line && !line.startsWith('#')).map(line => { const parts = line.split(/\s+/); return { pattern: parts[0], owners: parts.slice(1).filter(value => value.startsWith('@')).map(value => value.slice(1)) }; }); const owners = {}; for (const file of files) for (const rule of rules) if (globRegex(rule.pattern).test(file)) owners[file] = rule.owners; return owners; }
  async mergeRequirements(projectId, request) { const project = this.projects.get(projectId); const repository = this.projects.repositories.pathFor(project); const output = await this.projects.repositories.run(['diff', '--name-only', `${request.targetBranch}...${request.sourceBranch}`, '--'], { cwd: repository }); const files = output.stdout.split('\n').filter(Boolean); const ownerMap = await this.codeOwners(project, files); const rulesets = this.matchingRules(projectId, request.targetBranch).filter(item => item.enforcement === 'active'); const requiredReviewers = new Set(rulesets.flatMap(item => item.requiredReviewers)); if (rulesets.some(item => item.requireCodeOwners)) for (const owners of Object.values(ownerMap)) for (const owner of owners) requiredReviewers.add(owner); return { files, ownerMap, rulesets, requiredReviewers: [...requiredReviewers], requiredApprovals: Math.max(0, ...rulesets.map(item => item.requiredApprovals || 0)), dismissStaleApprovals: rulesets.some(item => item.dismissStaleApprovals), requireMergeQueue: rulesets.some(item => item.requireMergeQueue), requiredQualityGates: [...new Set(rulesets.flatMap(item => item.requiredQualityGates || []))] }; }
  async simulate(projectId, input) { const required = { read: 'guest', push: 'developer', merge: 'maintainer', administer: 'owner' }[input.action]; if (!required) throw new Error('Policy action is invalid'); const permission = input.at ? this.explainAt(projectId, input.userId, required, input.at) : this.explain(projectId, input.userId, required); const branch = text(input.branch || 'main', 'Branch', { max: 1024, required: true }); const rulesets = this.matchingRules(projectId, branch); const blockers = []; if (!permission.allowed) blockers.push(permission.explanation || `No active role satisfies ${required}`); if (input.action === 'merge' && rulesets.some(item => item.enforcement === 'active' && item.requireMergeQueue)) blockers.push('Merge queue is required'); return { action: input.action, branch, evaluatedAt: permission.evaluatedAt || new Date().toISOString(), allowed: blockers.length === 0, blockers, permission, matchedRulesets: rulesets }; }
}

module.exports = { PolicyService, globRegex, branchMatches };
