const crypto = require('node:crypto');

function previewSignature(secret, timestamp, body) { return crypto.createHmac('sha256', secret).update(`${timestamp}.${body}`).digest('hex'); }
function cleanServiceUrl(value, label = 'URL') { const url = new URL(value); const local = ['127.0.0.1', 'localhost', '::1'].includes(url.hostname); if ((url.protocol !== 'https:' && !(local && url.protocol === 'http:')) || url.username || url.password || url.hash) throw new Error(`${label} must use clean HTTPS (or loopback HTTP)`); return url.href; }
function targetUrl(value) { return cleanServiceUrl(value, 'Preview target'); }

class PreviewService {
  constructor({ store, projects, provisionerUrl = '', provisionerSecret = '' }) { this.store = store; this.projects = projects; this.provisionerUrl = provisionerUrl ? cleanServiceUrl(provisionerUrl, 'Preview provisioner') : ''; this.provisionerSecret = provisionerSecret; if (this.provisionerSecret && this.provisionerSecret.length < 32) throw new Error('Preview provisioner secret must contain at least 32 characters'); }
  enabled() { return Boolean(this.provisionerUrl && this.provisionerSecret); }
  list(projectId) { this.projects.get(projectId); return this.store.snapshot().previewEnvironments.filter(item => item.projectId === projectId); }
  async create(projectId, iid, input, actor) { if (!this.enabled()) throw Object.assign(new Error('Preview provisioner is not configured'), { statusCode: 503 }); const project = this.projects.get(projectId); const request = this.store.snapshot().mergeRequests.find(item => item.projectId === projectId && item.iid === iid); if (!request) throw Object.assign(new Error('Merge request not found'), { statusCode: 404 }); const commitSha = (await this.projects.repositories.run(['rev-parse', `refs/heads/${request.sourceBranch}`], { cwd: this.projects.repositories.pathFor(project) })).stdout.trim(); const hours = Math.max(1, Math.min(168, Number(input.expiresHours) || 24)); const payload = { action: 'create', project: project.slug, mergeRequestIid: iid, commitSha, targetUrl: targetUrl(input.targetUrl), expiresAt: new Date(Date.now() + hours * 3600_000).toISOString() }; const result = await this._call(payload); const item = { id: crypto.randomUUID(), projectId, mergeRequestIid: iid, commitSha, targetUrl: payload.targetUrl, url: result.url, state: 'active', createdBy: actor, createdAt: new Date().toISOString(), expiresAt: payload.expiresAt }; return this.store.update(state => { state.previewEnvironments.push(item); return item; }, { actor, action: 'preview.create', target: item.id }); }
  async remove(projectId, id, actor) { const item = this.store.snapshot().previewEnvironments.find(value => value.id === id && value.projectId === projectId); if (!item) throw Object.assign(new Error('Preview environment not found'), { statusCode: 404 }); await this._call({ action: 'delete', url: item.url }); return this.store.update(state => { const current = state.previewEnvironments.find(value => value.id === id); current.state = 'deleted'; current.deletedAt = new Date().toISOString(); return current; }, { actor, action: 'preview.delete', target: id }); }
  async cleanup() { const expired = this.store.snapshot().previewEnvironments.filter(item => item.state === 'active' && Date.parse(item.expiresAt) <= Date.now()); const results = []; for (const item of expired) { try { results.push(await this.remove(item.projectId, item.id, 'system:preview-expiry')); } catch (error) { results.push(this.store.update(state => { const current = state.previewEnvironments.find(value => value.id === item.id); current.lastCleanupError = error.message; current.lastCleanupAttemptAt = new Date().toISOString(); return current; }, { actor: 'system:preview-expiry', action: 'preview.cleanup_failed', target: item.id })); } } return results; }
  async _call(input) { const body = JSON.stringify(input); const timestamp = String(Math.floor(Date.now() / 1000)); const response = await fetch(this.provisionerUrl, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Kitsune-Timestamp': timestamp, 'X-Kitsune-Signature': `sha256=${previewSignature(this.provisionerSecret, timestamp, body)}` }, body, signal: AbortSignal.timeout(30_000) }); let result; try { result = await response.json(); } catch { result = {}; } if (!response.ok) throw Object.assign(new Error(`Preview provisioner failed: ${result.error || response.status}`), { statusCode: 502 }); return result; }
}

module.exports = { PreviewService, previewSignature, targetUrl, cleanServiceUrl };
