function symbols(lines) { const patterns = [/^\s*(?:export\s+)?(?:async\s+)?(?:function|class)\s+([A-Za-z_$][\w$]*)/, /^\s*(?:def|class)\s+([A-Za-z_]\w*)/, /^\s*(?:public|private|protected)?\s*(?:static\s+)?(?:function\s+)?([A-Za-z_]\w*)\s*\(/]; const found = new Set(); for (const line of lines) for (const pattern of patterns) { const match = pattern.exec(line.replace(/^[-+ ]/, '')); if (match) found.add(match[1]); } return [...found]; }
function parseDiff(output) { const files = []; let current = null; let hunk = null; for (const line of output.split('\n')) { if (line.startsWith('diff --git ')) { if (current) files.push(current); const match = /^diff --git a\/(.+) b\/(.+)$/.exec(line); current = { oldPath: match?.[1] || '', path: match?.[2] || '', additions: 0, deletions: 0, hunks: [], symbols: [] }; hunk = null; } else if (current && line.startsWith('@@')) { const match = /^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@(.*)$/.exec(line); hunk = { oldStart: Number(match?.[1]), oldLines: Number(match?.[2] || 1), newStart: Number(match?.[3]), newLines: Number(match?.[4] || 1), heading: match?.[5]?.trim() || '', lines: [] }; current.hunks.push(hunk); } else if (hunk && (/^[ +-]/.test(line)) && !line.startsWith('+++') && !line.startsWith('---')) { hunk.lines.push(line); if (line.startsWith('+')) current.additions += 1; if (line.startsWith('-')) current.deletions += 1; } } if (current) files.push(current); for (const file of files) file.symbols = symbols(file.hunks.flatMap(item => item.lines)); return files; }

class ReviewService {
  constructor({ projects, store, policy = null }) { this.projects = projects; this.store = store; this.policy = policy; }
  async semanticDiff(projectId, iid) { const project = this.projects.get(projectId); const request = this.store.snapshot().mergeRequests.find(item => item.projectId === projectId && item.iid === iid); if (!request) throw Object.assign(new Error('Merge request not found'), { statusCode: 404 }); const repository = this.projects.repositories.pathFor(project); const [diff, source] = await Promise.all([this.projects.repositories.run(['diff', '--find-renames', '--unified=3', `${request.targetBranch}...${request.sourceBranch}`, '--'], { cwd: repository }), this.projects.repositories.run(['rev-parse', `refs/heads/${request.sourceBranch}`], { cwd: repository })]); const requirements = this.policy ? await this.policy.mergeRequirements(projectId, request) : null; return { projectId, mergeRequestIid: iid, sourceCommit: source.stdout.trim(), files: parseDiff(diff.stdout), requirements };
  }
}

module.exports = { ReviewService, parseDiff, symbols };
