const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { JsonStore } = require('../src/server/json-store');
const { GitRepositoryService } = require('../src/server/git-repository-service');
const { ProjectService } = require('../src/server/project-service');
const { ProviderImportService } = require('../src/server/provider-import-service');
const { SecretVault } = require('../src/server/secret-vault');
const { WorkItemService } = require('../src/server/work-item-service');
const { ReviewService } = require('../src/server/review-service');
const { PolicyService } = require('../src/server/policy-service');
const { CollaborationRefService } = require('../src/server/collaboration-ref-service');
const { ForgeMeshService } = require('../src/server/forge-mesh-service');
const { ChangeIntelligenceService } = require('../src/server/change-intelligence-service');
const { PolicyEvidenceService } = require('../src/server/policy-evidence-service');
const { ChangeBundleService } = require('../src/server/change-bundle-service');
const { AttentionService } = require('../src/server/attention-service');
const { secretRedaction } = require('../src/server/ai-service');

test('sovereign collaboration refs, Forge Mesh, impact and portable bundles round-trip', async t => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'kitsune-sovereign-')); t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const repositories = new GitRepositoryService({ repositoriesPath: path.join(root, 'repositories'), allowFileRemotes: true });
  const source = path.join(root, 'source'); fs.mkdirSync(source); await repositories.run(['init', '--initial-branch=main'], { cwd: source });
  await repositories.run(['config', 'user.name', 'Test'], { cwd: source }); await repositories.run(['config', 'user.email', 'test@example.test'], { cwd: source });
  fs.writeFileSync(path.join(source, 'package.json'), JSON.stringify({ name: '@demo/core' })); fs.writeFileSync(path.join(source, 'index.js'), 'function stable() { return true; }\n'); await repositories.run(['add', '.'], { cwd: source }); await repositories.run(['commit', '-m', 'main'], { cwd: source });
  await repositories.run(['checkout', '-b', 'feature'], { cwd: source }); fs.mkdirSync(path.join(source, 'migrations')); fs.writeFileSync(path.join(source, 'migrations', '001.sql'), 'ALTER TABLE demo ADD COLUMN value TEXT;\n'); await repositories.run(['add', '.'], { cwd: source }); await repositories.run(['commit', '-m', 'feature'], { cwd: source });
  const store = new JsonStore(path.join(root, 'database.json')); const vault = new SecretVault('ab'.repeat(32)); const providerImports = new ProviderImportService(); const projects = new ProjectService({ store, repositories, providerImports, secretVault: vault });
  const project = await projects.import({ namespace: 'demo', name: 'core', sourceUrl: new URL(`file:///${source.replaceAll('\\', '/')}`).href, sourceProvider: 'git' }, 'owner');
  const consumer = await projects.import({ namespace: 'demo', name: 'consumer', sourceUrl: new URL(`file:///${source.replaceAll('\\', '/')}`).href, sourceProvider: 'git' }, 'owner');
  const auth = { canProject: () => true }; const policy = new PolicyService({ store, projects, auth }); const workItems = new WorkItemService({ store, projects, policy }); const reviews = new ReviewService({ projects, store, policy });
  const request = workItems.createMergeRequest(project.id, { title: 'Schema change', sourceBranch: 'feature', targetBranch: 'main' }, 'alice');
  const collaboration = new CollaborationRefService({ store, projects, dataPath: root }); collaboration.record(project.id, 'merge_request.created', { iid: request.iid }, 'alice'); const published = await collaboration.publish(project.id, 'alice'); assert.match(published.objectId, /^[a-f0-9]{40,64}$/); const read = await collaboration.read(project.id); assert.equal(read.verified, true); assert.equal(read.payload.collections.mergeRequests[0].iid, request.iid);
  const remote = path.join(root, 'remote.git'); await repositories.run(['clone', '--bare', source, remote], { cwd: root }); const mesh = new ForgeMeshService({ store, projects, providerImports, secretVault: vault }); const configured = mesh.add(project.id, { provider: 'git', name: 'backup', url: new URL(`file:///${remote.replaceAll('\\', '/')}`).href, codeMode: 'push', metadataAuthority: 'observe' }, 'owner'); const meshResult = await mesh.sync(project.id, configured.id, 'owner'); assert.equal(meshResult.remote.lastError, null);
  const intelligence = new ChangeIntelligenceService({ store, projects, reviews, policy }); intelligence.addLink(consumer.id, { toProjectId: project.id, kind: 'runtime' }, 'owner'); const impact = await intelligence.impact(project.id, request.iid); assert.ok(impact.riskScore >= 20); assert.equal(impact.affectedProjects[0].id, consumer.id);
  const evidence = new PolicyEvidenceService({ store, projects, policy, workItems, qualityGates: { statuses: () => [] }, collaborationRefs: collaboration }); const bundles = new ChangeBundleService({ store, projects, policyEvidence: evidence, collaborationRefs: collaboration, dataPath: root }); const bundle = await bundles.create(project.id, request.iid, 'alice'); const document = JSON.parse(bundles.read(project.id, bundle.id).content); assert.equal(bundles.verify(document).verified, true); const imported = await bundles.import(consumer.id, document, 'bob'); assert.match(imported.importedBranch, /^kitsune-import\//);
  store.update(state => { state.mirrorConflicts.push({ id: 'conflict-1', projectId: project.id, type: 'git-ref', key: 'refs/heads/main', state: 'open', detectedAt: new Date().toISOString() }); return null; }); const attention = new AttentionService({ store, projects, auth, policy }); const inbox = attention.inbox({ id: 'root', username: 'root', admin: true }); assert.equal(inbox[0].type, 'mirror-conflict'); attention.update(inbox[0].key, { acknowledged: true }, { id: 'root', username: 'root' }); assert.ok(!attention.inbox({ id: 'root', username: 'root', admin: true }).some(item => item.key === inbox[0].key));
  const redacted = secretRedaction('api_key=super-secret-value Bearer abcdefghijklmnopqrstuvwxyz'); assert.equal(redacted.count, 2); assert.doesNotMatch(redacted.value, /super-secret-value/);
});
