<?php

class Modules_KitsuneGit_WebServer extends pm_Hook_WebServer
{
    public function getDomainNginxConfig(pm_Domain $domain)
    {
        return $this->directives($domain);
    }

    public function getDomainNginxProxyConfig(pm_Domain $domain)
    {
        return $this->directives($domain);
    }

    private function directives(pm_Domain $domain)
    {
        $selected = strtolower(trim((string) pm_Settings::get('domain', '')));
        $name = strtolower(trim((string) $domain->getName()));
        if ($selected === '' || $name !== $selected || pm_Settings::get('proxyMode', 'managed') !== 'managed') return '';
        $port = max(1024, min(65535, (int) pm_Settings::get('appPort', '4780')));
        return "# KitsuneGIT — generated by the Plesk WebServer hook\n"
            . "rewrite ^/(?!\\.well-known(?:/|$)|__kitsune_git_internal__$).* /__kitsune_git_internal__ last;\n\n"
            . "location = /__kitsune_git_internal__ {\n"
            . "    internal;\n"
            . "    proxy_pass http://127.0.0.1:" . $port . "\$request_uri;\n"
            . "    proxy_http_version 1.1;\n"
            . "    proxy_request_buffering off;\n"
            . "    proxy_buffering off;\n"
            . "    proxy_read_timeout 3600s;\n"
            . "    proxy_send_timeout 3600s;\n"
            . "    client_max_body_size 0;\n"
            . "    proxy_set_header Host \$host;\n"
            . "    proxy_set_header X-Real-IP \$remote_addr;\n"
            . "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;\n"
            . "    proxy_set_header X-Forwarded-Proto \$scheme;\n"
            . "    proxy_set_header Upgrade \$http_upgrade;\n"
            . "    proxy_set_header Connection \"upgrade\";\n"
            . "}\n";
    }
}
